//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int id { get; set; }
        public string dates { get; set; }
        public string CO { get; set; }
        public string NOx { get; set; }
        public string ParticleLevel { get; set; }
    }
}
